version: '3.8'

services:
  app:
    build: .
    image: laravel12-app
    container_name: laravel12-app
    restart: unless-stopped
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  webserver:
    image: nginx:alpine
    container_name: laravel12-webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: laravel12-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-laravel}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: laravel12-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  postgres-data:
  redis-data: